"""
YouTube Live Streaming Integration helper
"""
import json
import os
import sys
import time
from datetime import datetime, timedelta
from typing import Dict, Optional

# Try imports
try:
    import requests
except ImportError:
    print("❌ Error: 'requests' library is missing. Install it with: pip install requests")
    sys.exit(1)

def get_rtmp_url(token_path: str, title: str = "Lofi Music Stream 24/7 ☕", description: str = "Generated by Lofi Video Generator", start_time: Optional[datetime] = None, end_time: Optional[datetime] = None) -> str:
    """
    Create a live broadcast on YouTube and return the RTMP ingestion URL.
    """
    if not os.path.exists(token_path):
        raise FileNotFoundError(f"Token file not found: {token_path}")
        
    with open(token_path, 'r') as f:
        creds = json.load(f)
        
    access_token = creds.get('access_token')
    if not access_token:
        # Check for nested format often used by pickle/auth libs
        access_token = creds.get('token')
        
    if not access_token:
        raise ValueError("Token file must contain 'access_token' or 'token'")

    headers = {
        'Authorization': f'Bearer {access_token}',
        'Content-Type': 'application/json',
        'Accept': 'application/json'
    }
    
    # 1. Create Broadcast
    print("📡 Creating YouTube Live Broadcast...")
    
    # Use provided start time or current time
    if not start_time:
        start_time = datetime.utcnow()
    
    start_iso = start_time.strftime('%Y-%m-%dT%H:%M:%S.000Z')
    
    broadcast_body = {
        "snippet": {
            "title": title,
            "description": description,
            "scheduledStartTime": start_iso
        },
        "status": {
            "privacyStatus": "public" 
        },
        "contentDetails": {
            "enableAutoStart": True,
            "enableAutoStop": True
        }
    }
    
    if end_time:
        broadcast_body["snippet"]["scheduledEndTime"] = end_time.strftime('%Y-%m-%dT%H:%M:%S.000Z')
    
    url_broadcast = "https://www.googleapis.com/youtube/v3/liveBroadcasts?part=snippet,status,contentDetails"
    resp = requests.post(url_broadcast, headers=headers, json=broadcast_body)
    
    if resp.status_code != 200:
        raise RuntimeError(f"Failed to create broadcast: {resp.text}")
        
    broadcast_data = resp.json()
    broadcast_id = broadcast_data['id']
    print(f"✅ Broadcast created: https://youtu.be/{broadcast_id}")
    
    # 2. Create Stream settings (Simplified for 1080p)
    print("🔗 Creating Video Stream settings...")
    stream_body = {
        "snippet": {
            "title": f"Lofi Stream Key - {int(time.time())}"
        },
        "cdn": {
            "frameRate": "30fps",
            "ingestionType": "rtmp",
            "resolution": "1080p"
        }
    }
    
    url_stream = "https://www.googleapis.com/youtube/v3/liveStreams?part=snippet,cdn"
    resp_stream = requests.post(url_stream, headers=headers, json=stream_body)
    
    if resp_stream.status_code != 200:
        raise RuntimeError(f"Failed to create stream: {resp_stream.text}")
        
    stream_data = resp_stream.json()
    stream_id = stream_data['id']
    
    ingestion_address = stream_data['cdn']['ingestionInfo']['ingestionAddress']
    stream_name = stream_data['cdn']['ingestionInfo']['streamName']
    
    rtmp_url = f"{ingestion_address}/{stream_name}"
    
    # 3. Bind Broadcast to Stream
    print("🔗 Binding broadcast to stream...")
    bind_url = f"https://www.googleapis.com/youtube/v3/liveBroadcasts/bind?id={broadcast_id}&part=id&streamId={stream_id}"
    resp_bind = requests.post(bind_url, headers=headers)
    
    if resp_bind.status_code != 200:
        raise RuntimeError(f"Failed to bind broadcast: {resp_bind.text}")
        
    print(f"✅ Stream Ready! RTMP URL obtained.")
    return rtmp_url, broadcast_id
